### ISSUE TITLE
Keep ObjectURL origin

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#116]
While expanding a given ObjectURL in storage.List method, keep a reference to the the original expandable form.

For example;

originalSrc: `s3://bucket/prefix/obj*`
expandedSrc: `s3://bucket/prefix/object1.gz`

`expandedSrc.Origin()` should return `originalSrc`.

**Comment by sonmezonur** [comment]
Since fs and s3 behave differently, we cannot set one original URL to source URLs on the storage layer.

* S3 expands sources according to the given prefix. That is why we can set the original URL.  (its origin is concrete and cannot have multiple origins). 
-- s3://bigtmp/bucket/*
   --- s3://bigtmp/bucket/testfile.txt (its source URL is s3://bigtmp/bucket/*)
   --- s3://bigtmp/bucket/prefix/testfile.txt (its source URL is s3://bigtmp/bucket/*)

* FS expands globs first and then walks through the directory. That is why it needs to keep the recursive hierarchy inside the URL (its origin can have origin). 
--  base/*
   --- base/testfile.txt (its source URL is base/*)
   --- base/dir (its source URL is base/*)
      ---- base/dir/testfile.txt (its source URL isbase/dir)

Making this change won't make any improvement in the codebase. I prefer not to implement this feature.
