### ISSUE TITLE
Add cross region transfer support

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#155]
Currently s5cmd doesn't support cp/mv operations between different s3 buckets. We need a way to specify the source region via a flag.

`awscli` provides `--source-region <value>` flag to support this feature.

**Comment by TomGudman** [comment]
I believe I have the same problem. I am trying to move a bucket to a **different** region. Unfortunately, it seems `s5cmd` expects the source and destination buckets to be in the same region. 

Example of copying from the us-west-2 to eu-west-1 (in the purpose of moving)
```
AWS_DEFAULT_REGION=us-west-2  s5cmd cp s3://source-us/* s3://destination-eu/
[..]
ERROR "cp s3://source-us/file1 s3://destination-us/file1": BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region at endpoint '' status code: 301, request id: , host id:
[..]
```
I would suggest something similar to @igungor but what's best : `--source-region` or `--destination-region`?

In the mean time, I will revert to `s4cmd`, then `s3cmd` and finally `awscli` if it turns out to be that complicated to copy cross region ;-)

**Comment by igungor** [comment]
Though it doesn't matter that much whether if it's `source-region` or `destination-region`,  I think the former is better since we have familiarity from `awscli`.
