### ISSUE TITLE
cp command incorrectly infers MIME type

### ISSUE THREAD

**Issue by chipzoller** [peak/s5cmd#214]
When using s5cmd and the `cp` command on a set of statically-generated web files to upload to an S3 bucket, the MIME types are not being correctly inferred. This causes some of them (ex. CSS files) to be fetched with the wrong response headers being returned. When using awscli and the `sync` command, for example, this is not an issue and the files are uploaded correctly.

Produces error:
`s5cmd cp -s -n -u <local_dir> s3://bucket_name`

Success:
`aws s3 sync --size-only --delete <local_dir> s3://bucket_name`

**Comment by fbarotov** [comment]
Hi, 

Thanks for reporting the issue. 

Currently, `s5cmd` infers content type of a file by reading some bytes of it and making use of `http.DetectContentType`, which does not detect specific type of a file. For example, if we create two files `foo.css` and `bar.js` with valid css and js contents,  using `http.DetectContentType` gives `text/plain; charset=utf-8` as content type for both of the files. However, their content types are `text/css; charset=utf-8` and `text/javascript; charset=utf-8`. 

It seems golang community uses `http.DetectContentType` and libraries such as [mimetype](https://github.com/gabriel-vasile/mimetype) and [filetype](https://github.com/h2non/filetype). Unfortunately none of the above options support e.g., `css filetype` inference. 

One solution would be, rather than reading contents of the file, we could just look at the file extension. There is go standard library [mime](https://golang.org/pkg/mime/) that correctly infers content type from the extension. For instance, `mime.TypeByExtension(".css") == "text/css; charset=utf-8"`

So, what do others think?

**Comment by igungor** [comment]
@fbarotov sounds good. if no extension is found, we can fallback to `http.DetectContentType`.

**Comment by chipzoller** [comment]
It may also be a useful addition to have a CLI flag that allows users to control how or if MIME types will be inferred.

**Comment by favoyang** [comment]
This fix is good. Please consider making a new release.
