### ISSUE TITLE
'cp -n' performance

### ISSUE THREAD

**Issue by plaisted** [peak/s5cmd#293]
Copy command with "no clobber" performs worse than I expected on large batch copies. Few notes:
- From my testing a 'cp -n' that copies no files is actually slightly slower than a 'cp' command that transfers and overwrites all of the files.
- This is for copies of thousands of files from network drive to a high performance on premise s3 instance.
- Currently s5cmd loops through all source files and checks each individually against the destination to see if destination exists. This results in multiple s3 API calls per file.
- I would expect that grabbing a file listing from both src and dest, comparing, and then copy only the required files would perform much better in nearly all scenarios (I'm doing this for mine instead of using s5cmd and it's much faster)

**Comment by igungor** [comment]
Hey,

Performance will be worse if you enable no-clobber because we need to send an HeadObject API call to check if we should override the destination, as you mention.

There's a new `sync` subcommand that does very similar to what you mentioned on your last bullet.

We don't have plans to change no-clobber logic, but you could use `sync` for better performance.

Thanks.
