### ISSUE TITLE
cp command downloads file from S3 even though the file does not exist on the S3 bucket

### ISSUE THREAD

**Issue by harisbr** [peak/s5cmd#348]
When cp command is executed to download a file from the S3 bucket I get the AWS error in console 'NoSuchKey: The specified key does not exist.' but the file with the same name is created on my local storage.
Is there any way to prevent this behaviour?

**Comment by ocakhasan** [comment]
Hi @harisbr, this should not happen. Can you please provide the `s5cmd` version and steps to reproduce the problem. We need a bit more detail to handle the issue.

**Comment by harisbr** [comment]
Hi @ocakhasan, thank you for the response.
Here are all details:
- version is 0.0.0-dev, I've installed it using Go, not sure if I did something wrong, I suppose it installed the latest version from the master branch
- executed command: 
`s5cmd cp s3://harisbr-test/filename.txt .downloads/`

This S3 bucket is empty, no files there.
I am sending you the screenshot of the error as well as the created file in the downloads folder.

![error](https://user-images.githubusercontent.com/15093185/131849875-58da7ae3-2d5d-4afd-beb8-4ce340d27bc6.png)
![file](https://user-images.githubusercontent.com/15093185/131849888-d4c6fa14-3712-42c1-ba49-656f6bc89696.png)

**Comment by ocakhasan** [comment]
Hi again @harisbr, 
I tried to debug the code and this below steps happens:
1. Since this is a download task, [`doDownload`](https://github.com/peak/s5cmd/blob/a0791f85e9908bc17d6fc85af9ac3cc1f4947eb1/command/cp.go#L462) is called. 
2. Then it tries to download the file, but it gives an error.  You can check it from [here](https://github.com/peak/s5cmd/blob/a0791f85e9908bc17d6fc85af9ac3cc1f4947eb1/command/cp.go#L486).
3. Since there is an error, we need to delete the generated file (filename.txt in your case), but when I tried to delete the file, [code part](https://github.com/peak/s5cmd/blob/a0791f85e9908bc17d6fc85af9ac3cc1f4947eb1/command/cp.go#L488), windows give me an error saying
```
remove deneme/filename.txt The process cannot access the file because it is being used by another process.
```
When I tried the same command in ubuntu, it works just fine, currently this seems to be a windows problem and there should be a fix in the new release, so stay tuned.
