### ISSUE TITLE
custom region doesn't work if bucket is specified

### ISSUE THREAD

**Issue by sihara** [peak/s5cmd#354]
custom reason works for bucket listing, but it doesn't work object listing. 
<pre>
$ cat ~/.aws/credentials 
[default]
aws_access_key_id = AKIA991Z6427QRER7O91
aws_secret_access_key = HBwlovGPG2u9bVAcytO+a97GI4m3K7JT1RkrvzNh
region = jp

$ ./s5cmd version 
v1.4.0-rc.1-a0791f8

$ ./s5cmd --endpoint-url http://s3ds-1 ls 
2021/09/20 01:08:01  s3://bucket1

$ ./s5cmd --endpoint-url http://s3ds-1 ls s3://bucket1
ERROR "ls s3://bucket1": AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'jp' status code: 400, request id: 611C446F010F3B13, host id: 611E5582312F22A8

**Comment by seruman** [comment]
Hi @shiara, sorry to hear that you're experiencing this. We're aware of this issue as it's already brought out multiple times; #325, #317, #314. We already have an open issue #320 and a PR #331 to address it. 

Since precedence changes would break usage of auto region detection, we're planning to fix this on next major release v2.0.0, hopefully in the following months.

Closing in favour of #320.

**Comment by sihara** [comment]
@seruman I'm testing s5cmd against DDN S3 Data service (https://www.ddn.com/download/ddn-data-services/) which can be running on DDN's parallel filesystem (EXAScaler/Lustre). S3 Data Service is very scalable and high performance and allows accessing to same name service of EXAScaler/Lustre.
I've done testing of several S3 client utilities (s3cmd, awscli, s3curl, etc) and they have been working well so far. I found s5cmd and it sounds like very fast. So, It's time to test s5cmd and benchmark the performance on DDN S3 Data service. :)
looking forward to getting fix for this region issue in new release sooner!
