### ISSUE TITLE
sync is not working if file name or directory contain space

### ISSUE THREAD

**Issue by masterlf** [peak/s5cmd#397]
Hi,
It seems s5cmd sync can not handle file names with space. sync then generate cp error like such:

ERROR "cp /zfs-pool/00 photo/0829 bla bla/_MG_5332.CR2 s3://aws_bucket/backup/40_photo/0829 bla bla/_MG_5332.CR2": expected source and destination arguments

Would it be possible to contain the name in quotes or something so that the command is not confused with what is the name and path and what are arguments?

thx

**Comment by sonmezonur** [comment]
Hello @masterlf . #409 should fix this issue. Could you confirm if it works for setup?

**Comment by stefanoabbate** [comment]
@sonmezonur I am experiencing the same problem while using wildcards:

`s5cmd --endpoint-url https://<s3endpoint> sync --delete s3://<bucket-name>/mydir/anotherdir/* s3://<bucket-name>/yourdir/anotherdir/`

I get some errors if there are one or more files with a whitespace in their name (files are out of my control):

`ERROR "cp s3://<bucket-name>/mydir/anotherdir/dir1/dir2/dir3/dir4/name en.pdf cp s3://<bucket-name>/mydir/yourdir/dir1/dir2/dir3/dir4/name en.pdf": NoSuchKey: The specified key does not exist. status code: 404, request id: f9e866a5d34d825a8c87, host id: f9e866a5d34d825a8c87`

Is this bug fixed by #409 ? s5cmd version is v2.0.0-35bb2fa

**Comment by matthiassb** [comment]
Can we reopen this please? It is not fixed in `v2.1.0-3efbbe8`
