### ISSUE TITLE
Feature Request - download intervals/sleep

### ISSUE THREAD

**Issue by autronix** [peak/s5cmd#462]
Hello,

A bit of context for the feature request.
I've been using s5cmd to download a large data set for work and I've experienced an issue associated with my internet provider.
According to my provider, there are no download restrictions on the 3Gbps line that I'm using, however every time I use s5cmd to download a ~4.5Tb package, their "distribution center" seems to be applying a blocking rule, which essentially cuts off my entire internet for about 6 minutes before letting me go back online.

At this point, I'm experiencing 5 min download, 6 min downtime consistently if I let it run.

The feature request would be to be able to set a download interval of X amount of min/secs and a sleep time of x amount of min/secs.

In my specific use case, this would about to letting s5cmd run the download for 4 minutes, take a 20s break then start over until it finishes (applicable to the sync or cp commands).

**Comment by igungor** [comment]
Hi,

Since the feature you requested is highly specific to your setup, I don't think we'd accept such a feature.

#433 issue may solve your problem if it is accepted.

There're a couple of external tools that you could use to throttle your network interface bandwidth, or s5cmd process bandwidth, but the most easy solution I think is `pv`:

```bash
cat 1G | pv -L 1M | s5cmd pipe s3://bigtmp/ibrahim/s5cmd/1G-throttled
00MiB 0:00:07 [1004KiB/s] [                     <=>                       ]
```

With above command, 1GB file is uploaded to S3 with max 1MB/s, which might help your case. `s5cmd pipe` command is not released yet but you could build it from master.
