### ISSUE TITLE
How to use 'Specifying credentials'?

### ISSUE THREAD

**Issue by TyeolRik** [peak/s5cmd#474]
Sorry for noob question. But I can't figure out how to use 'Specifying credentials' as README mentioned.

According to [Specifying credentials](https://github.com/peak/s5cmd#specifying-credentials),

There is ```--credentials-file``` flag in s5cmd. But, it doesn't. Is there any proper manual for using that flag?

Below is my terminal (CentOS 8 Stream, s5cmd: 2.0.0-35bb2fa)

```bash
[root@node1 s5cmd]# ls -al
total 12184
drwxr-xr-x. 2 root root        125 Jul 25 03:20 .
dr-xr-x---. 8 root root       4096 Jul 22 01:37 ..
-rw-r--r--. 1 1001 docker    15204 Jul  4 05:23 CHANGELOG.md
-rw-r--r--. 1 root root        116 Jul 25 03:20 dashboard_credential
-rw-r--r--. 1 root root        116 Jul 25 03:19 johndoe_credential
-rw-r--r--. 1 1001 docker     1061 Jul  4 05:23 LICENSE
-rw-r--r--. 1 1001 docker    21362 Jul  4 05:23 README.md
-rwxr-xr-x. 1 1001 docker 12419072 Jul  4 05:25 s5cmd
```

```bash
[root@node1 s5cmd]# cat ./johndoe_credential
[default]
aws_access_key_id = SLF*****
aws_secret_access_key = LrX*****
```

```bash
[root@node1 s5cmd]# ./s5cmd --no-sign-request --credentials-file ./johndoe_credential --endpoint-url http://172.22.4.101:80 ls
Incorrect Usage: flag provided but not defined: -credentials-file
See 's5cmd --help' for usage
```

```bash
[root@node1 s5cmd]# ./s5cmd --credentials-file ./johndoe_credential --endpoint-url http://172.22.4.101:80 ls
Incorrect Usage: flag provided but not defined: -credentials-file
See 's5cmd --help' for usage
```

**Comment by Kucukaslan** [comment]
Hi,

This feature is planned for the incoming release. Since the master branch is used for development, feature is also included in the readme. You can refer to older version of readme at the time of release at [here](https://github.com/peak/s5cmd/tree/v2.0.0#readme) in case you need.

If you really need this feature you can [build](https://github.com/peak/s5cmd#build-from-source) s5cmd from the master branch. Otherwise, you can continue using the default [AWS credential file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where) which you can create with `aws configure` command and then use s5cmd without needing to specify `--credentials-file` flag.

ps. FYI, We have edited your comment to redact the aws...key values. If they were real keys, we strongly suggest you to [change](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_RotateAccessKey) them (delete & create new keys).

**Comment by TyeolRik** [comment]
Thanks for your kindness, care about keys. Of course, that keys are test keys :) I will build that on my own with master branch as your recommendation. Thanks!
