### ISSUE TITLE
--profile is missing

### ISSUE THREAD

**Issue by az-z** [peak/s5cmd#535]
hello,
 for https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz  
```
(base) [az@fedora bin]$ s5cmd version
v2.0.0-35bb2fa
(base) [az@fedora bin]$ env | grep AWS
(base) [az@fedora bin]$
(base) [az@fedora bin]$ s5cmd ls -profile duke 
Incorrect Usage: flag provided but not defined: -profile

Name:
  ls - list buckets and objects

Usage:
  ls [options] argument
....

(base) [az@fedora bin]$ s5cmd -profile duke ls
Incorrect Usage: flag provided but not defined: -profile
See 's5cmd --help' for usage


```
whereas with aws cli:  
```
(base) [az@fedora bin]$ aws --profile duke s3 ls
2022-04-08 10:52:38 cdk-XXXXXX-us-east-1
```
Please let me know if I'm overlooking something.

P.S. Just to be clear. This version does pick up AWS_PROFILE env var.

**Comment by Kucukaslan** [comment]
Hi,

Sorry for the inconvenience, but this feature is planned for the [incoming release](https://github.com/orgs/peak/projects/1). Since the master branch is used for development, feature is also included in the readme. You can refer to older version of readme at the time of release at [here](https://github.com/peak/s5cmd/tree/v2.0.0#readme) in case you need.

If you really need this feature you can [build](https://github.com/peak/s5cmd#build-from-source) s5cmd from the master branch.

**Comment by az-z** [comment]
Muhammad,
Thank for the reply. I thought I took the officially released version. No?

**Comment by Kucukaslan** [comment]
Yes you did use the officially released version. But the `--profile` flag is not supported in that release.

`--profile` flag will, hopefully, be supported/added in next release (whose release date is not determined yet).

**Comment by az-z** [comment]
Got it. Thank you for responding.
It will be great to see profiles supported.

**Comment by Kucukaslan** [comment]
> Got it. Thank you for responding.

You're welcome.

**Comment by phajduk** [comment]
@Kucukaslan maybe you can publish the latest master as a latest tag in hub docker? You keep tagging docker images with versions like `v2.0.0` anyway, so we can assume `latest` docker tag is just the latest main branch.

**Comment by turian** [comment]
@Kucukaslan just curious when the next release is planned, if it is known no.

**Comment by igungor** [comment]
`--profile` flag is added with `v2.1.0` release. #453
