### ISSUE TITLE
`s5cmd` help is misleading

### ISSUE THREAD

**Issue by bounlu** [peak/s5cmd#555]
`s5cmd` help provides Examples:

  
```
Examples:
...
  06. Upload matching files to S3 bucket
     > s5cmd cp dir/*.gz s3://bucket/
...
```

But the above example does not work unless the text including the wildcard character (*) is enclosed with quotation marks.

This works instead:

```
Examples:
  06. Upload matching files to S3 bucket
     > s5cmd cp "dir/*.gz" s3://bucket/
```

**Comment by szeitlin** [comment]
I'm also getting this error. In my case I'm sending this to a remote machine, where it looks like the wildcard I'm using is getting expanded prematurely, and then the code is expecting exactly 2 arguments for the `cp` command, so instead of seeing e.g.

`cp sourcefile destination`

what it's actually seeing is

`cp file1 file2 file3 file4 .... etc. destination`

and the error is thrown here where it looks for exactly 2 arguments: https://github.com/peak/s5cmd/blob/master/command/cp.go#L843

So I tried the single quotes, e.g. 

`cp 'sourcefile*' destination` but that didn't work. 

`cp "sourcefile*" destination` with double quotes didn't work, either. 

`cp \'sourcefile*\' destination` works from the command line, using the slashes to escape the quotes

and from python, I ended up having to make it a raw string in order to get that to work, like so:

`r" cp \'sourcefile*\' destination"`
