### ISSUE TITLE
Neither '--include' nor '--exclude' taking effect for 'sync'

### ISSUE THREAD

**Issue by landscapepainter** [peak/s5cmd#659]
Hi, I'm currently trying out with the most recent version provided, 2.2.1.

```
$ s5cmd version
v2.2.1-be63977
```

Trying to use `--exclude` and `--include` options with `sync`, but it does not seem to take effect as you can see from the following example:
```
$ s5cmd sync --exclude "storage-demo" --exclude "r2_s3_storage.yaml" /home/gcpuser/yaml s3://s3-copy-testing
cp /home/gcpuser/yaml/gcs_storage.yaml s3://s3-copy-testing/yaml/gcs_storage.yaml
cp /home/gcpuser/yaml/storage-demo s3://s3-copy-testing/yaml/storage-demo
cp /home/gcpuser/yaml/ubuntu.yaml s3://s3-copy-testing/yaml/ubuntu.yaml
cp /home/gcpuser/yaml/gcs_sync_storage.yaml s3://s3-copy-testing/yaml/gcs_sync_storage.yaml
cp /home/gcpuser/yaml/r2_s3_storage.yaml s3://s3-copy-testing/yaml/r2_s3_storage.yaml
```

As you can see, `storage-demo` and `r2_s3_storage.yaml` are all included and uploaded. I'm trying to run the mix of both options to strictly include the files I specify and exclude the rest of the files in the given source such as: 
`$ s5cmd sync --destination-region us-east-2 --no-follow-symlinks --exclude="*" --include "r2_s3_storage.yaml" --include "storage_demo" /home/gcpuser/yaml s3://s3-copy-testing
`
And running the above does not print out any outputs and does not upload any files. My expectation was to have `/home/gcpuser/yaml/r2_s3_storage.yaml` and `/home/gcpuser/yaml/storage_demo` to be uploaded to `s3://s3-copy-testing` and exclude rest of the files in `/home/gcpuser/yaml`.

Wondering if this is a bug or I have issues in my usage. Also tried out with `2.2.0` and `2.1.0` as well, but got same results(`--exclude` did not work with `2.1.0`)

I'm using following machine:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

```

**Comment by ahmethakanbesel** [comment]
Hi there,

I see that your source objects have the prefix `/home/gcpuser/yaml`. This means that the  `--exclude` flag should be like `--exclude "*storage-demo"` and `--exclude "*r2_s3_storage.yaml"` (or you may include the exact prefix rather than a wildcard).

The `--exclude` flag tells `s5cmd` to skip any objects that match the specified pattern ([Using Exclude and Include Filters](https://github.com/peak/s5cmd?tab=readme-ov-file#using-exclude-and-include-filters)). In your case, the pattern `*` matches all objects. So, if you use the `--exclude="*"` flag, `s5cmd` will skip all of the objects in the source directory.  In this case, you don't need to use the `--exclude` flag because the `--include` flag will only transfer objects that match the specified wildcard.

I hope this helps.

**Comment by landscapepainter** [comment]
@ahmethakanbesel Thanks for the fix! Adding in the asterisk was the key and I ended up using --exclude "*/storage-demo" and --exclude "*/r2_s3_storage.yaml". I'm closing as it's resolved.
