### ISSUE TITLE
run input syntax is not documented

### ISSUE THREAD

**Issue by PerMildner** [peak/s5cmd#713]
As far as I can see there is no documentation except for the `README.md` file and it does not say anything about the syntax of the input to the `s5cmd run` command.

In particular it does not say anything about how to quote file/object names with whitespace or other special characters.

**Comment by kucukaslan** [comment]
The relevant code snippet
https://github.com/peak/s5cmd/blob/c1c7ee35acfc16aaf4a2b060129aa60b75bb5ef5/command/run.go#L105-L147

It appears that:

- each line is trimmed of spaces via [strings.TrimSpace](https://pkg.go.dev/strings@go1.22.1#TrimSpace)
- empty lines and the lines starting with `#` are ignored
- the line is split via [kballard/go-shellquote.Split]( https://pkg.go.dev/github.com/kballard/go-shellquote#Split) _"...according to **/bin/sh**'s word-splitting rules"_
- later the line is parsed to _command_ and the rest (flags and arguments) via https://pkg.go.dev/flag#FlagSet.Parse

AFAIU: we can say that each line must be formatted so that running `s5cmd {line}` on the shell would work as intended.

**Comment by ilkinulas** [comment]
same as  #714
