### ISSUE TITLE
Please create a new release with updated `github.com/lanrat/extsort` version

### ISSUE THREAD

**Issue by gkowarzyk** [peak/s5cmd#717]
Hello,

The `github.com/lanrat/extsort` library has created a new release tag (`v1.0.1`), which includes the latest fixes, and changes the license from `GPL` to an `Apache v2` license.

Please create a new release with the updated `github.com/lanrat/extsort` version, as it would allow `s5cmd` to include the new license in its dependencies instead.

Thanks in advance!

**Comment by Redeys** [comment]
`takeme`takemeit of noting ### toadsi`version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Create security fix PRs only
    open-pull-requests-limit: 0


  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Create security fix PRs only
    open-pull-requests-limit`

**Comment by Redeys** [comment]
[**_account_**](tu 

> bitfis h _it's not about then [**)_**](bit of the game ### code)

**Comment by kucukaslan** [comment]
Hi team,

What do you think about upgrading extsort's version?

I suppose updating go.mod and vendor/ would be enough. If needed I can open a PR.

Ideally a github action, using https://github.com/google/go-licenses, to check license compatibility can be added to ensure such a mistake won't happen again but I cannot promise doing it. 


I also want to make a kind of reflection (retro?) since I was the one added this dependency 😅 .
I vaguely remember that I checked the license because I was interested in FOSS and inter-compability of GNU-GPL license variants with ours. 
at https://github.com/lanrat/extsort/issues/3 we see that project license was changed to Apache in 2021 (a year before we started using it) at GitHub repo. Probably, I merely checked the GitHub repo and thought it is fine, and did not investigate further.

Bests
